module.exports = {
  CONNECT: "connect",
  USER_TYPE_ADMIN: "admin",
  CLASS_NAME_TABLE: "class_name",
  SUBJECT_NAME_TABLE: "subject_name",
  TIME_SLOT_TABLE: "time_slot",
  STUDENT_TABLE: "student",
  TEACHER_TABLE: "teacher",
  DIVISION_TABLE_NAME: "divisions",
  DISTRICT_TABLE_NAME: "districts",
  UPAZILA_TABLE_NAME: "upazilas",
  UNION_TABLE_NAME: "unions",
  USER_TYPE_STUDENT: "student",
  USER_TYPE_TEACHER: "teacher",
  WEEKS_TABLE_NAME: "week",
  DURATION_TABLE_NAME: "duration",
  GROUP_NAME_TABLE_NAME: "group_name",
  ACADEMIC_YEAR_TABLE_NAME: "academic_year",
  CLASS_ROUTINE_TABLE_NAME: "class_routine",
  USER_TYPE_PARENT: "parent",
  MONGO_DB_NAME: "school_database",
  ATTENDANCE_TABLE_NAME: "attendance",
  EXAM_TYPE_TABLE_NAME: "exam_type",
  EXAM_ROUTINE_TABLE_NAME: "exam_routine",
  EXAM_MARKS_TABLE_NAME: "exam_mark",
  GRADING_TABLE_NAME: "grading",
  FEE_TYPE_TABLE_NAME: "fee_type",
  CLASS_FEES_TABLE_NAME: "class_fees",
  FEES_COLLECTION_TABLE_NAME: "fee_collection",
  CLASS_ROOM_TABLE_NAME: "class_room",
  CLASS_STUDENT_TABLE_NAME: "class_student",
  HOMEWORK_COLLECTION_NAME: "home_work",
  NOTICE_COLLECTION_NAME: "notice",
  APP_LANGUAGE_COLLECTION_NAME: "app_language",
  HOLIDDAY_COLLECTION_NAME: "holiday",
  

  LANGUAGE_BN:'BN',
  LANGUAGE_EN:'EN',
};
